"""
Contract test for the prompt-creator skill.

Generated by skill-create as a starting scaffold -- fill in real
assertions against this skill's declared inputs/outputs before
considering it done, per DEFINITION_OF_DONE.md step 2.
"""

import json
import re
from pathlib import Path

try:
    import yaml
except ImportError:  # fall back to the stdlib parser below
    yaml = None

SKILL_DIR = Path(__file__).parent
REQUIRED_METADATA_FIELDS = [
    "name",
    "version",
    "category",
    "layer",
    "rank",
    "description",
    "inputs",
    "outputs",
    "dependencies",
    "stack",
    "runtime-independent",
    "logging",
]


def test_skill_json_valid_and_complete():
    data = json.loads((SKILL_DIR / "skill.json").read_text(encoding="utf-8"))
    for field in REQUIRED_METADATA_FIELDS:
        assert field in data, f"skill.json missing required field: {field}"
    assert data["name"] == "prompt-creator"
    assert data["category"] == "craft"


# The stdlib frontmatter parser below is copied from skill-create's main.py, so
# without PyYAML this test accepts the same shapes `--audit` does: single-line
# plain, single-quoted or double-quoted values. It is a strict subset of YAML;
# any other form needs PyYAML (see requirements.txt).
NEEDS_PYYAML = 'install PyYAML (python3 -m pip install -r requirements.txt) to parse this form'
_PLAIN_FIRST_INDICATORS = set('!"#%&\'*,-:>?@[]`{|}')
_YAML_SAFE_CHARS_RE = re.compile('^[\t\n -~\xa0-‧\u202a-\ud7ff\ue000-�𐀀-\U0010ffff]*$')
_YAML_NON_STRING_PLAIN_RE = re.compile('^(?:yes|Yes|YES|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF|[-+]?(?:[0-9][0-9_]*)\\.[0-9_]*(?:[eE][-+][0-9]+)?|\\.[0-9][0-9_]*(?:[eE][-+][0-9]+)?|[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+\\.[0-9_]*|[-+]?\\.(?:inf|Inf|INF)|\\.(?:nan|NaN|NAN)|[-+]?0b[0-1_]+|[-+]?0[0-7_]+|[-+]?(?:0|[1-9][0-9_]*)|[-+]?0x[0-9a-fA-F_]+|[-+]?[1-9][0-9_]*(?::[0-5]?[0-9])+|<<|~|null|Null|NULL|=|[0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}(?:[Tt]|[ \\t]+)[0-9]{1,2}:[0-9]{2}:[0-9]{2}(?:\\.[0-9]*)?(?:[ \\t]*(?:Z|[-+][0-9]{1,2}(?::[0-9]{2})?))?)$')
_FRONTMATTER_KEY_RE = re.compile('^[A-Za-z_][A-Za-z0-9_-]*$')
_SINGLE_QUOTED_RE = re.compile("^'((?:[^']|'')*)'$")
_SURROGATE_ESCAPE_RE = re.compile('\\\\u[dD][89a-fA-F][0-9a-fA-F]{2}')


def _parse_scalar_without_yaml(key, value):
    """Decode one single-line scalar, or raise ValueError saying why this
    fallback cannot. Accepts only forms where yaml.safe_load returns the
    identical str: plain, single-quoted, JSON-style double-quoted."""
    if not value:
        raise ValueError(
            f"{key!r} has an empty value, or a value on following lines "
            f"(multi-line, nested or null): {NEEDS_PYYAML}")
    first = value[0]
    if first == '"':
        if _SURROGATE_ESCAPE_RE.search(value):
            raise ValueError(
                f"{key!r} is a double-quoted scalar with a \\uD800-\\uDFFF surrogate escape, "
                f"which PyYAML decodes differently from JSON: {NEEDS_PYYAML}")
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError:
            raise ValueError(
                f"{key!r} is a double-quoted scalar this fallback cannot decode (it accepts "
                f"JSON-style escapes only, with nothing after the closing quote, e.g. no trailing "
                f"comment): {NEEDS_PYYAML}")
        if not isinstance(decoded, str):
            raise ValueError(f"{key!r} is not a double-quoted string: {NEEDS_PYYAML}")
        return decoded
    if first == "'":
        quoted = _SINGLE_QUOTED_RE.match(value)
        if not quoted:
            raise ValueError(
                f"{key!r} is a single-quoted scalar this fallback cannot decode (a lone quote must "
                f"be doubled, and nothing may follow the closing quote): {NEEDS_PYYAML}")
        return quoted.group(1).replace("''", "'")
    if first in "|>":
        raise ValueError(f"{key!r} is a block (literal or folded) scalar: {NEEDS_PYYAML}")
    if first in "[{":
        raise ValueError(f"{key!r} is a flow collection (list or mapping): {NEEDS_PYYAML}")
    if first in "&*!":
        raise ValueError(f"{key!r} uses a YAML anchor, alias or tag: {NEEDS_PYYAML}")
    if first in _PLAIN_FIRST_INDICATORS:
        raise ValueError(
            f"{key!r} is a plain scalar starting with the YAML indicator {first!r}; quote it, "
            f"or {NEEDS_PYYAML}")
    if "\t" in value:
        raise ValueError(f"{key!r} is a plain scalar containing a tab: {NEEDS_PYYAML}")
    if ": " in value or value.endswith(":"):
        raise ValueError(
            f"{key!r} is a plain scalar containing ': ' (invalid YAML; quote the value)")
    if " #" in value:
        raise ValueError(
            f"{key!r} is a plain scalar containing ' #', which YAML reads as a comment; "
            f"quote the value, or {NEEDS_PYYAML}")
    if _YAML_NON_STRING_PLAIN_RE.match(value):
        raise ValueError(
            f"{key!r} is a plain scalar YAML reads as a number, boolean, null or date, not a "
            f"string; quote it, or {NEEDS_PYYAML}")
    return value


def _parse_frontmatter_without_yaml(block):
    """Stdlib fallback (EDS-39): a mapping of `key: <single-line scalar>` lines,
    a strict subset of YAML (see _parse_scalar_without_yaml). Whatever it
    returns, yaml.safe_load returns too; anything it cannot prove that for
    raises ValueError naming PyYAML as the way to parse it."""
    block = block.replace("\r\n", "\n")
    if not _YAML_SAFE_CHARS_RE.match(block):
        raise ValueError(
            f"frontmatter contains a control character or a YAML line-break character: {NEEDS_PYYAML}")
    data = {}
    for line in block.split("\n"):
        if not line.strip(" "):
            continue
        if line[0] in " \t":
            raise ValueError(
                f"indented frontmatter line {line!r} (continuation or nested value): {NEEDS_PYYAML}")
        if line[0] == "#":
            continue
        key, sep, value = line.partition(":")
        if not sep or not _FRONTMATTER_KEY_RE.match(key) or (value and value[0] != " "):
            raise ValueError(f"unparseable frontmatter line: {line!r}")
        data[key] = _parse_scalar_without_yaml(key, value.strip(" "))
    if not data:
        raise ValueError("frontmatter is not a YAML mapping")
    return data


def _parse_frontmatter(block):
    if yaml is not None:
        return yaml.safe_load(block)
    return _parse_frontmatter_without_yaml(block)


def test_skill_md_has_valid_frontmatter():
    text = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    assert match, "SKILL.md must start with YAML frontmatter"
    frontmatter = _parse_frontmatter(match.group(1))
    assert frontmatter["name"] == "prompt-creator"
    assert isinstance(frontmatter["description"], str) and frontmatter["description"].strip(), "SKILL.md needs a non-empty description"


def _skill_md_body():
    text = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
    return text.split("\n---\n", 1)[1]


def test_description_says_when_to_trigger():
    text = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    desc = _parse_frontmatter(match.group(1))["description"].lower()
    for word in ("write", "draft", "tidy", "prompt", "claude code", "cowork", "subagent"):
        assert word in desc, f"description should mention {word!r}"


def test_skill_md_covers_behaviours_and_targets():
    body = _skill_md_body().lower()
    for needle in (
        "read the session first",
        "one batch",
        "askuserquestion",
        "fresh claude code session",
        "ticket workflow",
        "cowork session prompt",
        "one ticket per subagent",
        "stop condition",
        "report format",
        "code block",
        "jira comment",
        "do not post anywhere without a ticket",
    ):
        assert needle in body or needle.replace("jira comment", "comment on it") in body, f"SKILL.md missing: {needle}"


def test_skill_md_carries_hard_limits_and_self_check():
    body = _skill_md_body()
    for needle in ("merges stay with Brad", ".github/workflows/", "Notion drafts", "feature/", "bugfix/", "hotfix/"):
        assert needle in body, f"SKILL.md missing hard limit: {needle}"
    assert body.count("- [ ]") >= 5, "SKILL.md needs the self-check list"


def test_skill_md_stands_alone():
    body = _skill_md_body()
    assert "TODO" not in body
    assert "main.py" not in body, "installed plugin ships no scripts; SKILL.md must not depend on them"
    assert not (SKILL_DIR / "main.py").exists()


if __name__ == "__main__":
    test_skill_json_valid_and_complete()
    test_skill_md_has_valid_frontmatter()
    test_description_says_when_to_trigger()
    test_skill_md_covers_behaviours_and_targets()
    test_skill_md_carries_hard_limits_and_self_check()
    test_skill_md_stands_alone()
    print("All prompt-creator contract tests passed.")
